package com.company;

import static org.junit.Assert.assertTrue;


import org.graphwalker.core.machine.ExecutionContext;
import org.graphwalker.java.annotation.GraphWalker;


/**
 * Implements the GraphWalker model: src/main/resources/SmallTest.json
 * <p/>
 * The interface SmallTest, that SomeSmallTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn compile
 */
@GraphWalker(value = "random(edge_coverage(100))")
public class SomeSmallTest extends ExecutionContext implements SmallTest {

	private boolean firstTimeAnotherAction = false;
  @Override
  public void e_FirstAction() {
	  firstTimeAnotherAction = true;
    System.out.println("Running: e_FirstAction");
  }

  @Override
  public void e_AnotherAction() {

    System.out.println("Running: e_AnotherAction");
    assertTrue(firstTimeAnotherAction);
    firstTimeAnotherAction = false;
  }

  @Override
  public void e_SomeAction() {
    System.out.println("Running: e_SomeAction");
  }

  @Override
  public void e_SomeOtherAction() {
    System.out.println("Running: e_SomeOtherAction");
  }

  @Override
  public void v_VerifyInitialState() {
    System.out.println("Running: v_VerifyInitialState");
  }

  @Override
  public void v_VerifyFirstAction() {
    System.out.println("Running: v_VerifyFirstAction");
  }

  @Override
  public void v_NewVertex() {
    System.out.println("Running: v_NewVertex");
  }
}
